FROM node:14.4.0-alpine as build
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile --silent
RUN npm install react-scripts@3.4.1 -g --silent
COPY . ./
RUN npm run build
RUN yarn global add serve
CMD ["serve", "-s", "build"]