
FROM node:14.4.0-alpine

RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app

WORKDIR /home/node/app

COPY package*.json ./

USER node

RUN yarn --silent
COPY . ./

COPY --chown=node:node . .

EXPOSE 3000

ENTRYPOINT ["/home/node/app/start.sh"]
